name: CI
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  task12:
    env:
      using: 'node20'
      main: 'main.js'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Show name
        run: echo "My name is Ivan Yushchuk"
